name: Deploy WebGL to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload WebGL Site
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy WebGL to GitHub Pages
        uses: actions/deploy-pages@v2
